language: node_js
node_js: node
sudo: required
dist: precise
before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get install ffmpeg
  - ffmpeg -version