language: node_js
node_js: node
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg
  - ffmpeg -version